name: Build APK (Flutter 3.35.1)

on:
  push:
    branches: [ flet ]
    tags:
      - 'v*'
  workflow_dispatch:

env:
  # FLUTTER_VERSION: 3.35.1
  PYTHON_VERSION: 3.12.1
  PYTHONIOENCODING: utf-8 

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    # 1. Fetch code
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # 2. Install Python
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    # 3. Install Flet-CLI
    - name: Install Flet
      run: python -m pip install flet


    # 4. Build APK
    - name: Build APK
      run: flet build apk

    # 5.  Release
    - name: Create release
      uses: softprops/action-gh-release@v2
      with:
        files: build/app/outputs/flutter-apk/app-release.apk        
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
